version: '3'
services:
  app:
    build: .
    ports:
    - "127.0.0.1:5000:5000"
    environment:
    - PORT=5000
    - SQL_HOST=db
    links:
    - db
    restart: always
  db:
    image: postgres:9-alpine
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - /docker/postgres/rsvg:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=rsvg
    - POSTGRES_PASSWORD=rsvg
    restart: always
